### ISSUE TITLE
not初回起動 && データがない ときのエラー処理

### ISSUE THREAD

**Issue by yykk3322** [leochoo/ios-sfcbustimer#13]
現状アプリが落ちる
けれど初回起動時にネット接続がない場合しか起こりえないので、そこまでurgentではない

**Comment by leochoo** [comment]
これはまだ問題？

**Comment by yykk3322** [comment]
YES
今はsaveできてなくても初回起動処理は終了するし
dataがなくてもgetNextBusが動こうとして落ちる
例外処理が必要！

**Comment by yykk3322** [comment]
@leochoo
