### ISSUE TITLE
currUserTimeに関して

### ISSUE THREAD

**Issue by leochoo** [leochoo/ios-sfcbustimer#27]

**Comment by leochoo** [comment]
現在global としてcurrUserTimeがあるけど、
mainとかgetNextBusは中でcurrUserTimeを取るので（それがもっと正確かも）、
globalのやつはなんのためのcurrUserTimeかな？
初期画面？

**Comment by yykk3322** [comment]
現状currUserTimeが登場するのは
main
getNextBus
DataUtils.jsonToDateObj
の3つだけど

そのどれの中でも、currUserTimeは現在時刻とイコールで、一意的(同じときに別の値になる可能性がない)

だからそれぞれの中で
現在時刻の変数を宣言してGETするよりは、グローバルに用意しておいて必要になるたびGETするのが
論理的にConsistencyがあるのでは、と考えた！

まあ各関数の中で作るのも動作的には支障ないしOKだと思う！ｗ
